mattermost/mattermost-plugin-starter-template

Makefile, build/setup.mk
A few more improvements that make the initial startup experience a bit better:
* warn upfront if go/dep/npm not available
* try to find dep in $GOPATH/bin if not installed globally
* only override variables if not externally defined, allowing manual override from commandline
* split up Makefile into a buid/setup.mk for simplicity
I started out here trying to fix Linux-specific issues, but didn't actually find anything that made this Makefile not-linux specific -- tested on Debian with the standard make installed. Can I get you to give this a shot on your machine to verify?
=> more Makefile improvements

Makefile, build/manifest/main.go, build/setup.mk, server/manifest.go, webapp/src/index.js, webapp/src/manifest.js
* define BUNDLE_NAME after including build/setup.mk (just for clarity, not correctness)
* separate plugin id from version with dash in bundle name to match Mattermost package
* fix various js/go idioms (some pre-existing!)
* fix error message
=> tweak plugin id/version injection

server/configuration.go, server/plugin.go
This accompanies the [server changes](https://github.com/mattermost/mattermost-server/pull/9519) to remove support for automatically unmarshalling a plugin's server configuration.
See also:
* https://github.com/mattermost/mattermost-plugin-demo/pull/7
* https://github.com/mattermost/mattermost-developer-documentation/pull/167
=> MM-12193: illustrate simplified, but safe configuration handling

server/Gopkg.lock, server/Gopkg.toml, server/plugin.go, server/plugin_test.go
This PR adds a hello world http method to the plugin. It also, and I think this more important, adds a test for this.
=> Add hello world http method

Makefile
This PR adds a `make help` target similar to the one on the Mattermost server. See https://github.com/mattermost/mattermost-server/blob/master/Makefile#L534.
The current list looks like this:
```
$ make help
all                            Checks the code style, tests, builds and bundles the plugin.
apply                          Propagates plugin manifest information into the server/ and webapp/ folders as required.
bundle                         Generates a tar bundle of the plugin for install.
check-style                    Runs govet and gofmt against all packages.
clean                          Clean removes all build artifacts.
deploy                         Installs the plugin to a (development) server.
dist                           Builds and bundles the plugin.
gofmt …
```
=> Add make help target

server/configuration.go
If the plugin leaves the configuration struct empty, go will optimize away allocations of the zero-width struct, failing the `setConfiguration` check that prevents a user from introducing race conditions.
The demo plugin has more extensive unit tests around configuration, but it also has a non-empty struct as such. I'm inclined /not/ to test this case in the sample plugin, because this is meant as a "copy and paste" way to get started, and if you add a configuration, the test would fail.
Fixes  #17
=> configuration: ignore an empty configuration struct in setConfiguration

Makefile
This PR adds a 'make coverage` command, which creates a coverage report for the server code.
The code isn't DRY but I don't know how to fix this without adding a new `test-server` target.
Is there a similar tool for webapp?
=> Add make coverage

plugin.json, server/manifest.go, webapp/src/manifest.js
This is recommended by semver.org (See https://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase)
It makes more clear that the first version is a minor version, **not** a patch version.
=> Start with version 0.1.0 instead of 0.0.1

Makefile
Instead of individual calls '&&' together, the deploy now checks each response for a valid result.
This  fixes problems on Ubuntu 16.04 when mysteriously, the <upload> && <enable> && ok || failed never works.
=> changed single expression plugin upload to validate responses

Makefile
`server/.depensure` doesn't exist any longer.
=> Fix make coverage

README.md
For anyone new to Go modules, it's worth adding some clarity on how to use this project in the event it remains located in the `$GOPATH`.
=> Clarify Go modules requirements.

Makefile, build/custom.mk
This PR adds support for custom makefiles. The custom makefile must be located under `build/custom.mk`. I don't see the need for making this customisable. I've added a empty file as a boiler plate.
Please note that custom targets will **not** be listed via `make help`. I tried fixing this but it took to much time. I would open a Help Wanted ticket for this, if there are no objections.
=> Add support for custom makefile

README.md, go.mod, plugin.json, public/hello.html, server/manifest.go, webapp/src/manifest.js
The name of this repo has been decided to change from `mattermost-plugin-sample` to `mattermost-plugin-starter-template`. As a result, any references to the original name in documentation needs to be updated, including this repo.
All the changes are pretty straightforward. One thing I am hesitant to change here is the id of the plugin itself. I'm not sure what implications the change would have. This may be irrelevant, but there was recently [discussion](https://community.mattermost.com/core/pl/kjjc9btof7be7q96x6o6acpj8o) about renaming the id of a plugin, and it seemed as if that was taboo.
I have included the id change here from `com.mattermost.sample-plugin` to `com.mattermost.plugin-starter-template`. Do you have an opinion on this @hanzei? …
=> [MM-14189] Update references to "mattermost-plugin-sample" to be "mattermost-plugin-starter-template"

Makefile
Assign `$GOPATH` if not set, and use same to get to `$GOPATH/bin` instead of assuming `$PATH` contains same.
=> avoid assuming $GOPATH is set

go.mod, go.sum, webapp/webpack.config.js
- replacing apache.com/thrift with github.com to solve network issue on make
- missing dangling comma in webpack.config.js
https://github.com/mattermost/mattermost-server/issues/12125
=> replacing apache.com/thrift with github.com to solve network issue

README.md
- ~~Avoids to use shields.io's badge~~
- Adds a useful link to the CircleCI pipeline results
cf. some usecase in a certain project: wbernest/mattermost-plugin-rssfeed#18
=> Add a link to the project status page on CircleCI

Makefile, build/deploy/main.go, build/setup.mk, go.mod, go.sum
A recent change to `make deploy` broke the ability to actually deploy the plugin successfully. Let's fix this once and for all by moving to a Go binary that can use the `Client4` API properly.
Relates-to: https://github.com/mattermost/mattermost-plugin-starter-template/issues/69.
Fixes: https://mattermost.atlassian.net/browse/MM-20610
=> make deploy reliable using Go

build/manifest/main.go, server/manifest.go
Fix invalid in import in `server/manifest.go`. This fixes the broken `master`. 
`master` broken due to https://github.com/mattermost/mattermost-plugin-starter-template/pull/76
=> Fix invalid import in manifest.go

.gitignore
PR https://github.com/mattermost/mattermost-plugin-starter-template/pull/80 incorrectly added `node_modules` to the root `.gitignore`.
=> Remove `node_modules` from root .gitignore

webapp/babel.config.js, webapp/webpack.config.js
Some babel transformations (such as rest/spread operators) are currently not available because `corejs` is not properly used in the babel config. This PR fixes that by including it.
This PR also pulls out the babel config, so Jest may properly have access to it.
https://mattermost.atlassian.net/browse/MM-22298
=> Add `corejs: 3`, and pull out babel config from webpack config

README.md, build/deploy/main.go
Introduce support for `MM_ADMIN_TOKEN` as an alternative to defining `MM_ADMIN_USERNAME` and `MM_ADMIN_PASSWORD`.
=> Allow make deploy using token

build/deploy/main.go
This removes a double print of the API response error message.
Old:
```
Failed to deploy: failed to login as admin: : Enter a valid email or username and/or password., : : Enter a valid email or username and/or password.,
```
New:
```
Failed to deploy: failed to login as admin: : Enter a valid email or username and/or password.,
```
Better, but still seems to have a strange error format returned from the server. I didn't have time to look into if this was fixed recently as my server is intentionally a bit out of date, but I wanted to note it.
=> Cleanup deploy error message

Makefile
Fixes makefile so if package.json is modified then `npm install` will be re-run.
Alternative to: https://github.com/mattermost/mattermost-plugin-starter-template/pull/93
=> Fix makefile to npm install when package.json changes.

Makefile
The environment variable `DEBUG` can have unwanted side effects in unrelated programs. This PR changes the expected variable to `MM_DEBUG` to avoid conflicts.
=> Rename DEBUG env var to MM_DEBUG

Makefile
Fixes incorrect location of public files when building.
=> Fix recursive copies in Makefile for OSX

.golangci.yml
Both linter haven't been proven useful and created more false positives then correct results.
https://community.mattermost.com/core/pl/r5fdx8xmp3na8er87zkt5pyqpy
=> Drop interfacer and goconst from golangci-lint config

Makefile
I've used the [wildcard function](https://www.gnu.org/software/make/manual/html_node/Wildcard-Function.html) to skip the `webapp/package.json` target dependency if it is missing.
Fixes https://github.com/mattermost/mattermost-plugin-starter-template/issues/112.
=> Skip the `webapp/package.json` if it is missing

build/sync/plan/git/file_history_test.go
This is to fix CI breakage ( https://app.circleci.com/pipelines/github/mattermost/mattermost-plugin-starter-template/428/workflows/508a6d30-001a-4087-b353-52dddc71683c/jobs/981 ) after landing https://github.com/mattermost/mattermost-plugin-starter-template/pull/128
=> Disable git file history test that relies on commits not being squashed in github PR merges.

build/sync/plan/checks.go, build/sync/plan/checks_test.go, build/sync/plan/git/file_history.go, build/sync/plan/git/file_history_test.go, build/sync/plan/git/testdata/testfile.txt, go.mod, go.sum
Improve file history related tests in the synchronization tool to not rely on the git history of the starter template repository.
Fixes #134
=> Synchronization tool file history tests modified to set up a temporary git repo

.golangci.yml
Disable the newly added `fieldalignment` check as it proves little value for new devs.
Fixes https://github.com/mattermost/mattermost-plugin-starter-template/issues/148
=> Disable fieldalignment golangci-lint check

Makefile, plugin.json
adding linux arm64 targets as well 
we are building linux/darwin arm64 targets now for server: https://github.com/mattermost/mattermost-server/pull/18491
n/a
=> add linux arm64 targets

README.md
```bash
./build/bin/pluginctl deploy com.coltonshaw.additional-banner dist/com.coltonshaw.additional-banner-1.5.1.tar.gz
2022/01/25 15:43:36 Connecting using local mode over /var/tmp/mattermost_local.socket
2022/01/25 15:43:36 Uploading plugin via API.
Failed: failed to upload plugin bundle: : Plugins and/or plugin uploads have been disabled., 
```
Plugin uploads are not enabled by default
=> Added Enable upload to plugins

.circleci/config.yml, .golangci.yml, server/plugin_test.go
- Update orb version
- Fix linter errors caused by `golangci-lint` update
https://github.com/mattermost/circleci-orbs/pull/35
=> Update orb version

Makefile
With the Apps plugin we've run into an issue (https://github.com/mattermost/mattermost-plugin-apps/pull/318) where cross compiling the plugin causes an issue as on cloud server a symbol was missing:
`error relocating plugins/com.mattermost.apps/server/dist/plugin-linux-amd64: __fprintf_chk: symbol not found`
By static linking the binary we not longer rely on a DL to be there.
Focalboard already disabled CGO: https://github.com/mattermost/focalboard/blob/d6e494ca295969322abca0f62228061161573dd7/mattermost-plugin/Makefile#L91-L105
https://mattermost.atlassian.net/browse/MM-43713
=> [MM-43713] Disable CGO for all builds

webapp/webpack.config.js
For some more context, see [here](https://community.mattermost.com/core/pl/1fkkx7pj1jrwffrc6drh3x71eh). The short version though is that we updated the web app to React 17, and there's a chance that plugins will have some issues with it because they're compiled with the React 16 version of ReactDOM. I'm submitting PRs to the 3 products, the demo plugin, and the plugin template to have them use the web app's version of React DOM to fix any immediate issues, but we'll want to properly migrate them to React 17 going forward.
https://mattermost.atlassian.net/browse/MM-47046
https://github.com/mattermost/mattermost-plugin-playbooks/pull/1489
https://github.com/mattermost/focalboard/pull/3861
https://github.com/mattermost/mattermost-plugin-todo/pull/190 …
=> MM-47046 Use version of React DOM provided by web app

plugin.json
Bump up min_server_version to match mattermost-server in go.mod
Fixes #172
=>  Bump up min_server_version to match mattermost-server in go.mod

server/plugin.go
The scheduled CI job that runs every day has been failing for about a month due to this linting rule. @hanzei Any way we can be notified of this, maybe through a webhook to Mattermost?
=> Fix ununsed param

.golangci.yml, server/plugin.go
=> Disable unused-parameter golangci check

Makefile, build/manifest/main.go
- Last week we had a bit of trouble where a plugin settings field type was wrong. The plugin was functional, but the manifest validation step in the marketplace `generate` step failed. Moving that validation step up to the plugin side will prevent that from happening again, https://github.com/mattermost/mattermost-plugin-calls/pull/689.
-  Sending this change upstream.
- https://mattermost.atlassian.net/browse/MM-57855
=> [MM-57855] Add manifest validation step

README.md
Updates the build badges to point to Github Actions instead of CircleCI.
=> docs: updated build badges to github actions links

webapp/package.json
Adds `emotion/react` to the webapp dependencies.
When migrating a plugin to the latest template, I found it had a missing dependency on `emotion/react`, referencing this line:
```javascript
export default class UserAttribute extends React.PureComponent {
```
Seems worth adding to the `package.json`. I picked a version of similar age to `emotion/core` and all seemed well.
=> Add emotion/react dependency

.golangci.yml, Makefile
Update golangci from v1.51.1 to <s>v1.59.1</s> v1.61.0
Fixes #204.
=> Update golangci to v1.61.0

Makefile
Effectively work around the following error (example from Playbooks):
```
plugin built at: dist/playbooks-+59740baf.tar.gz
./build/bin/pluginctl deploy playbooks dist/playbooks-+59740baf.tar.gz
2023/01/11 14:23:30 Connecting using local mode over /var/tmp/mattermost_local.socket
2023/01/11 14:23:30 Uploading plugin via API.
Failed: failed to upload plugin bundle: : Unable to find manifest for extracted plugin., open /var/folders/44/tv5rv9_j6r1bl4rj0qxpy1jh0000gn/T/plugintmp3335227689/plugin.json: no such file or directory
```
See also https://github.com/mattermost/mattermost-plugin-playbooks/pull/1745. I'm not sure how this hasn't made it into the starter template before now :(
None
=> Avoid issues on Darwin bundling the plugin

webapp/src/types/mattermost-webapp/index.d.ts
Small fix for this PR: https://github.com/mattermost/mattermost-plugin-starter-template/pull/222
=> Add all types for registry - change `options` argument for `registerAdminConsoleCustomSetting` to optional

Makefile
This pull request adds a helpful warning to the `Makefile` to alert developers when they are building the plugin with the default plugin ID. This encourages proper configuration before distribution.
N/A
Closes #152
=> chore: add warning for default plugin ID in Makefile during build

webapp/package-lock.json, webapp/package.json
`emotion/core` was renamed to `emotion/react` in [v11](https://emotion.sh/docs/emotion-11).
We have `emotion/react`, so we should remove the obsolete `emotion/core` now.
=> deps: remove emotion/core

webapp/package.json, webapp/src/index.tsx, webapp/src/manifest.test.tsx, webapp/src/react_fragment.test.tsx, webapp/tsconfig.json, webapp/webpack.config.js
When jest tests import a `jsx`/`tsx` module, they fail with this obscure error:
```
FAIL  src/react_fragment.test.tsx
● Test suite failed to run
TypeError: React.createContext is not a function
at Object.<anonymous> (node_modules/@emotion/react/dist/emotion-element-e89f38a3.cjs.dev.js:41:48)
at Object.<anonymous> (node_modules/@emotion/react/dist/emotion-react.cjs.dev.js:7:22)
```
The explanation is:
* The use of React fragments causes `emotion` to be loaded
* `emotion` also imports React with `require('react')`
* This causes an ambiguity for the jest loader. The `moduleDirectories` includes both `"node_modules"` and `""`, leading to ambiguity between the actual React module and `emotion/react`. The result of the import ends up being `undefined` which later leads to the error shown.
A …
=> Make import path specs consistent and fix error when running tests that use jsx/tsx
